apiVersion: v1
kind: Service
metadata:
  name: simplybyte-calc-svc
spec:
  selector:
    project: calculator
  type: NodePort
  ports:
    - port: 80           # service port (host-facing)
      targetPort: 5000   # container port your app listens on
      protocol: TCP
      nodePort: 30080    # optional fixed nodePort (30000-32767). Remove to auto-assign.
